### ISSUE TITLE
Can not flash ArrowOs with twrp

### ISSUE THREAD

**Issue by Jakarrrg** [ArrowOS-Devices/android_device_xiaomi_jasmine_sprout#1]
I am unable to flash ArrowOs with twrp. Every time I try it I get error 7. The only way I managed to flash ArrowOs is by following the instructions on PixelExperience page, as suggested, with the difference that I have to install twrp on boot-a and PE recovery on boot-b, enter twrp, flash repartition zip, enter PE recovery, factory reset, wipe-super super_empty, and then flash ArrowOs through adb sideload on PE recovery. After flashing ArrowOs, twrp on boot-a is replaced with ArrowOs recovery, and if I try reflashing twrp the Os is gone.

**Comment by iamimmanuelraj** [comment]
THere is no latest supported official recovery and also we have move to dynamic retrofit partition scheme. All notes and required steps will be said when new update comes out (mostly this month end)
